name: Run All Scripts
on: [push]

jobs:
  execute-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2
        with:
            fetch-depth: 2
      - name: Run any .sh file found
        run: |
          # نستخدم المقارنة بين الحالة القديمة والجديدة للـ push
          for script in $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.sh$'); do
              echo "جاري تشغيل السكريبت المضاف حديثاً: $script"
              chmod +x "$script"
              ./"$script"
              echo "-------------------------------------"
          done
